package com.gokanaz.kanazpad.utils

import android.content.Context
import com.gokanaz.kanazpad.data.model.Note
import org.apache.poi.xwpf.usermodel.XWPFDocument
import org.apache.poi.xwpf.usermodel.XWPFParagraph
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object DocxExporter {
    
    fun exportNoteToDocx(context: Context, note: Note): File {
        val fileName = "${note.title.replace(" ", "_")}_${System.currentTimeMillis()}.docx"
        val outputDir = File(context.getExternalFilesDir(null), "exports")
        if (!outputDir.exists()) {
            outputDir.mkdirs()
        }
        
        val outputFile = File(outputDir, fileName)
        val document = XWPFDocument()
        
        try {
            // Title
            val titlePara = document.createParagraph()
            titlePara.alignment = org.apache.poi.xwpf.usermodel.ParagraphAlignment.CENTER
            val titleRun = titlePara.createRun()
            titleRun.setText(note.title)
            titleRun.isBold = true
            titleRun.fontSize = 24
            
            // Empty line
            document.createParagraph()
            
            // Metadata
            val dateFormat = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
            val metaPara = document.createParagraph()
            val metaRun = metaPara.createRun()
            metaRun.setText("Created: ${dateFormat.format(note.createdAt)}")
            metaRun.addBreak()
            metaRun.setText("Updated: ${dateFormat.format(note.updatedAt)}")
            metaRun.addBreak()
            metaRun.setText("Words: ${note.getWordCount()} | Characters: ${note.getCharCount()}")
            metaRun.fontSize = 10
            metaRun.color = "808080"
            
            // Empty line
            document.createParagraph()
            document.createParagraph()
            
            // Content
            val lines = note.content.split("\n")
            for (line in lines) {
                val para = document.createParagraph()
                val run = para.createRun()
                
                when {
                    line.startsWith("# ") -> {
                        val text = line.substring(2)
                        run.setText(text)
                        run.isBold = true
                        run.fontSize = 20
                    }
                    line.startsWith("## ") -> {
                        val text = line.substring(3)
                        run.setText(text)
                        run.isBold = true
                        run.fontSize = 16
                    }
                    line.startsWith("### ") -> {
                        val text = line.substring(4)
                        run.setText(text)
                        run.isBold = true
                        run.fontSize = 14
                    }
                    line.startsWith("**") && line.endsWith("**") -> {
                        val text = line.substring(2, line.length - 2)
                        run.setText(text)
                        run.isBold = true
                    }
                    line.startsWith("*") && line.endsWith("*") && !line.startsWith("**") -> {
                        val text = line.substring(1, line.length - 1)
                        run.setText(text)
                        run.isItalic = true
                    }
                    else -> {
                        val cleanLine = line.replace(Regex("[`>\\[\\]]"), "")
                        run.setText(cleanLine)
                    }
                }
                
                run.fontSize = 12
            }
            
            // Footer
            document.createParagraph()
            document.createParagraph()
            val footerPara = document.createParagraph()
            footerPara.alignment = org.apache.poi.xwpf.usermodel.ParagraphAlignment.CENTER
            val footerRun = footerPara.createRun()
            footerRun.setText("Generated by Kanaz Pad (@GoKanaz)")
            footerRun.fontSize = 9
            footerRun.color = "CCCCCC"
            footerRun.isItalic = true
            
            // Save document
            FileOutputStream(outputFile).use { out ->
                document.write(out)
            }
            
        } finally {
            document.close()
        }
        
        return outputFile
    }
}
