package com.gokanaz.kanazpad.utils

import android.content.Context
import android.graphics.Color
import com.gokanaz.kanazpad.data.model.Note
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Text
import com.itextpdf.layout.properties.TextAlignment
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfExporter {
    
    fun exportNoteToPdf(context: Context, note: Note): File {
        val fileName = "${note.title.replace(" ", "_")}_${System.currentTimeMillis()}.pdf"
        val outputDir = File(context.getExternalFilesDir(null), "exports")
        if (!outputDir.exists()) {
            outputDir.mkdirs()
        }
        
        val outputFile = File(outputDir, fileName)
        val writer = PdfWriter(FileOutputStream(outputFile))
        val pdfDocument = PdfDocument(writer)
        val document = Document(pdfDocument)
        
        try {
            // Title
            val titleParagraph = Paragraph()
                .add(Text(note.title)
                    .setFontSize(24f)
                    .setBold()
                    .setFontColor(ColorConstants.BLACK))
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20f)
            document.add(titleParagraph)
            
            // Metadata
            val dateFormat = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
            val metaParagraph = Paragraph()
                .add(Text("Created: ${dateFormat.format(note.createdAt)}\n")
                    .setFontSize(10f)
                    .setFontColor(ColorConstants.GRAY))
                .add(Text("Updated: ${dateFormat.format(note.updatedAt)}\n")
                    .setFontSize(10f)
                    .setFontColor(ColorConstants.GRAY))
                .add(Text("Words: ${note.getWordCount()} | ")
                    .setFontSize(10f)
                    .setFontColor(ColorConstants.GRAY))
                .add(Text("Characters: ${note.getCharCount()}\n\n")
                    .setFontSize(10f)
                    .setFontColor(ColorConstants.GRAY))
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(30f)
            document.add(metaParagraph)
            
            // Content - split by lines and add
            val lines = note.content.split("\n")
            for (line in lines) {
                val cleanLine = line.replace(Regex("[#*>`\\-\\[\\]]"), "")
                
                val paragraph = when {
                    line.startsWith("# ") -> {
                        Paragraph(cleanLine)
                            .setFontSize(20f)
                            .setBold()
                            .setMarginTop(15f)
                            .setMarginBottom(10f)
                    }
                    line.startsWith("## ") -> {
                        Paragraph(cleanLine)
                            .setFontSize(16f)
                            .setBold()
                            .setMarginTop(12f)
                            .setMarginBottom(8f)
                    }
                    line.startsWith("### ") -> {
                        Paragraph(cleanLine)
                            .setFontSize(14f)
                            .setBold()
                            .setMarginTop(10f)
                            .setMarginBottom(6f)
                    }
                    else -> {
                        Paragraph(cleanLine)
                            .setFontSize(12f)
                            .setMarginBottom(5f)
                    }
                }
                
                document.add(paragraph)
            }
            
            // Footer
            val footerParagraph = Paragraph()
                .add(Text("\n\nGenerated by Kanaz Pad (@GoKanaz)")
                    .setFontSize(9f)
                    .setFontColor(ColorConstants.LIGHT_GRAY)
                    .setItalic())
                .setTextAlignment(TextAlignment.CENTER)
                .setFixedPosition(
                    40f,
                    30f,
                    pdfDocument.defaultPageSize.width - 80f
                )
            document.add(footerParagraph)
            
        } finally {
            document.close()
        }
        
        return outputFile
    }
    
    fun exportMultipleNotesToPdf(context: Context, notes: List<Note>, fileName: String): File {
        val outputFileName = "${fileName}_${System.currentTimeMillis()}.pdf"
        val outputDir = File(context.getExternalFilesDir(null), "exports")
        if (!outputDir.exists()) {
            outputDir.mkdirs()
        }
        
        val outputFile = File(outputDir, outputFileName)
        val writer = PdfWriter(FileOutputStream(outputFile))
        val pdfDocument = PdfDocument(writer)
        val document = Document(pdfDocument)
        
        try {
            notes.forEachIndexed { index, note ->
                // Title
                val titleParagraph = Paragraph()
                    .add(Text(note.title)
                        .setFontSize(24f)
                        .setBold())
                    .setMarginBottom(20f)
                document.add(titleParagraph)
                
                // Content
                val lines = note.content.split("\n")
                for (line in lines) {
                    val cleanLine = line.replace(Regex("[#*>`\\-\\[\\]]"), "")
                    val paragraph = Paragraph(cleanLine)
                        .setFontSize(12f)
                        .setMarginBottom(5f)
                    document.add(paragraph)
                }
                
                // Add page break if not last note
                if (index < notes.size - 1) {
                    document.add(Paragraph("\n\n"))
                }
            }
        } finally {
            document.close()
        }
        
        return outputFile
    }
}
